trigger: none

pool:
  name: Default

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '24.x'

- script: |
    npm install -g yarn
    yarn
    npx playwright install
  displayName: 'Instalar dependências'

- script: yarn run e2e
  displayName: 'Executar testes'

- script: |
    dir
    dir playwright-report
  condition: always()
  displayName: 'Verificar relatório'

- task: PublishPipelineArtifact@1
  condition: always()
  inputs:
    targetPath: 'playwright-report'
    artifact: 'playwright-report'