pipeline {
    agent any

    stages {

        stage('Instalar Dependências') {
            steps {
                bat 'yarn install --network-timeout 600000'
            }
        }

        stage('Instalar Browsers') {
            steps {
                bat 'npx playwright install'
            }
        }

        stage('Executar Testes') {
            steps {
                bat 'yarn run e2e'
            }
        }
    }
}