pipeline {
    agent {
        label 'windows'
    }

    stages {
        stage('Instalar Dependências') {
            steps {
                bat 'npm install -g yarn'
                bat 'yarn install --network-timeout 600000'
            }
        }

        stage('Instalar Browsers') {
            steps {
                bat 'npx playwright install'
            }
        }

        stage('Executar Testes') {
            steps {
                bat 'yarn run e2e'
            }
        }
    }

    post {
        always {
            publishHTML([
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'playwright-report',
                reportFiles: 'index.html',
                reportName: 'Relatório Playwright'
            ])
        }
    }
}